require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/player_games", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PlayerGame. As you add validations to PlayerGame, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PlayerGame.create! valid_attributes
      get player_games_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      player_game = PlayerGame.create! valid_attributes
      get player_game_url(player_game)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_player_game_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      player_game = PlayerGame.create! valid_attributes
      get edit_player_game_url(player_game)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PlayerGame" do
        expect {
          post player_games_url, params: { player_game: valid_attributes }
        }.to change(PlayerGame, :count).by(1)
      end

      it "redirects to the created player_game" do
        post player_games_url, params: { player_game: valid_attributes }
        expect(response).to redirect_to(player_game_url(PlayerGame.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PlayerGame" do
        expect {
          post player_games_url, params: { player_game: invalid_attributes }
        }.to change(PlayerGame, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post player_games_url, params: { player_game: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested player_game" do
        player_game = PlayerGame.create! valid_attributes
        patch player_game_url(player_game), params: { player_game: new_attributes }
        player_game.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the player_game" do
        player_game = PlayerGame.create! valid_attributes
        patch player_game_url(player_game), params: { player_game: new_attributes }
        player_game.reload
        expect(response).to redirect_to(player_game_url(player_game))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        player_game = PlayerGame.create! valid_attributes
        patch player_game_url(player_game), params: { player_game: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested player_game" do
      player_game = PlayerGame.create! valid_attributes
      expect {
        delete player_game_url(player_game)
      }.to change(PlayerGame, :count).by(-1)
    end

    it "redirects to the player_games list" do
      player_game = PlayerGame.create! valid_attributes
      delete player_game_url(player_game)
      expect(response).to redirect_to(player_games_url)
    end
  end
end
