require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/snack_games", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SnackGame. As you add validations to SnackGame, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SnackGame.create! valid_attributes
      get snack_games_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      snack_game = SnackGame.create! valid_attributes
      get snack_game_url(snack_game)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_snack_game_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      snack_game = SnackGame.create! valid_attributes
      get edit_snack_game_url(snack_game)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SnackGame" do
        expect {
          post snack_games_url, params: { snack_game: valid_attributes }
        }.to change(SnackGame, :count).by(1)
      end

      it "redirects to the created snack_game" do
        post snack_games_url, params: { snack_game: valid_attributes }
        expect(response).to redirect_to(snack_game_url(SnackGame.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SnackGame" do
        expect {
          post snack_games_url, params: { snack_game: invalid_attributes }
        }.to change(SnackGame, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post snack_games_url, params: { snack_game: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested snack_game" do
        snack_game = SnackGame.create! valid_attributes
        patch snack_game_url(snack_game), params: { snack_game: new_attributes }
        snack_game.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the snack_game" do
        snack_game = SnackGame.create! valid_attributes
        patch snack_game_url(snack_game), params: { snack_game: new_attributes }
        snack_game.reload
        expect(response).to redirect_to(snack_game_url(snack_game))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        snack_game = SnackGame.create! valid_attributes
        patch snack_game_url(snack_game), params: { snack_game: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested snack_game" do
      snack_game = SnackGame.create! valid_attributes
      expect {
        delete snack_game_url(snack_game)
      }.to change(SnackGame, :count).by(-1)
    end

    it "redirects to the snack_games list" do
      snack_game = SnackGame.create! valid_attributes
      delete snack_game_url(snack_game)
      expect(response).to redirect_to(snack_games_url)
    end
  end
end
